language: php

php:
  - 5.6

sudo: false

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: EscBasket
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/tvargasvicencio/EscBasket.git

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer global require 'phpmetrics/phpmetrics'
  - composer install --no-interaction

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - vendor/bin/phpunit

after_script:
  - chmod +x ./codeclimate.sh
  - ./codeclimate.sh

after_success:
  - - php $TRAVIS_BUILD_DIR/vendor/phpmetrics/phpmetrics/bin/phpmetrics --report-html=$TRAVIS_BUILD_DIR/report/PHPMetricsReport.html $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh