language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - chmod +x ./codeclimate.sh
  - ./codeclimate.sh

after_success:
  - coveralls